version: '3'

services:

  frontend:
    build:
      context: ./frontend
      dockerfile: frontend.Dockerfile
    ports:
      - "80:80"
    networks:
      - loki-network

  backend:
    build:
      context: ./backend
      dockerfile: backend.Dockerfile
    ports:
      - "8080:8080"
    networks:
      - loki-network

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    networks:
      - loki-network

  promtail:
    image: grafana/promtail:latest
    volumes:
      - /var/log:/var/log
    command: -config.file=/etc/promtail/promtail-config.yml
    ports:
      - "9080:9080"
    depends_on:
      - loki
    networks:
      - loki-network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - loki
    networks:
      - loki-network

networks:
  loki-network:

